version: '2'
services:
  web:
    image: tueffy/webgoredis
    depends_on:
    - redis
  lb:
    image: dockercloud/haproxy
    links:
    - web
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 80:80
  redis:
    image: redis
